/* --- Generated the 30/10/2018 at 9:38 --- */
/* --- heptagon compiler, version 1.05.00 (compiled sun. oct. 7 16:30:53 CET 2018) --- */
/* --- Command line: /home/gwen/.opam/4.04.0/bin/heptc -nocaus -simple-scheduler -target c main_controller.ept --- */

#ifndef MAIN_CONTROLLER_H
#define MAIN_CONTROLLER_H

#include "main_controller_types.h"
#include "main.h"
typedef struct Main_controller__main_ctrlr0_out {
  Main__version_type c_c_img_ver;
} Main_controller__main_ctrlr0_out;

void Main_controller__main_ctrlr0_step(int c_img_e, int c_img_r,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r, int pnr,
                                       int pnr_1, int pnr_10, int pnr_11,
                                       int pnr_12, int pnr_13, int pnr_2,
                                       int pnr_3, int pnr_4, int pnr_5,
                                       int pnr_6, int pnr_7, int pnr_8,
                                       int pnr_9,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr0_out* _out);

typedef struct Main_controller__main_ctrlr1_out {
  Main__version_type c_me_imu_ver;
} Main_controller__main_ctrlr1_out;

void Main_controller__main_ctrlr1_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int pnr, int pnr_1,
                                       int pnr_10, int pnr_11, int pnr_12,
                                       int pnr_13, int pnr_2, int pnr_3,
                                       int pnr_4, int pnr_5, int pnr_6,
                                       int pnr_7, int pnr_8, int pnr_9,
                                       Main__version_type pref_ver_12,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr1_out* _out);

typedef struct Main_controller__main_ctrlr2_out {
  Main__version_type c_me_img_ver;
} Main_controller__main_ctrlr2_out;

void Main_controller__main_ctrlr2_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_imu_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int pnr,
                                       int pnr_1, int pnr_10, int pnr_11,
                                       int pnr_12, int pnr_13, int pnr_2,
                                       int pnr_3, int pnr_4, int pnr_5,
                                       int pnr_6, int pnr_7, int pnr_8,
                                       int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr2_out* _out);

typedef struct Main_controller__main_ctrlr3_out {
  Main__version_type c_sl_ver;
} Main_controller__main_ctrlr3_out;

void Main_controller__main_ctrlr3_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_img_ver,
                                       Main__version_type c_me_imu_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int obj_14,
                                       int pnr, int pnr_1, int pnr_10,
                                       int pnr_11, int pnr_12, int pnr_13,
                                       int pnr_2, int pnr_3, int pnr_4,
                                       int pnr_5, int pnr_6, int pnr_7,
                                       int pnr_8, int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       Main__version_type pref_ver_14,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr3_out* _out);

typedef struct Main_controller__main_ctrlr4_out {
  Main__version_type c_oa_ver;
} Main_controller__main_ctrlr4_out;

void Main_controller__main_ctrlr4_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_img_ver,
                                       Main__version_type c_me_imu_ver,
                                       Main__version_type c_sl_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int obj_14,
                                       int obj_15, int pnr, int pnr_1,
                                       int pnr_10, int pnr_11, int pnr_12,
                                       int pnr_13, int pnr_2, int pnr_3,
                                       int pnr_4, int pnr_5, int pnr_6,
                                       int pnr_7, int pnr_8, int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       Main__version_type pref_ver_14,
                                       Main__version_type pref_ver_15,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr4_out* _out);

typedef struct Main_controller__main_ctrlr5_out {
  Main__version_type c_tl_ver;
} Main_controller__main_ctrlr5_out;

void Main_controller__main_ctrlr5_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_img_ver,
                                       Main__version_type c_me_imu_ver,
                                       Main__version_type c_oa_ver,
                                       Main__version_type c_sl_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int obj_14,
                                       int obj_15, int obj_16, int pnr,
                                       int pnr_1, int pnr_10, int pnr_11,
                                       int pnr_12, int pnr_13, int pnr_2,
                                       int pnr_3, int pnr_4, int pnr_5,
                                       int pnr_6, int pnr_7, int pnr_8,
                                       int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       Main__version_type pref_ver_14,
                                       Main__version_type pref_ver_15,
                                       Main__version_type pref_ver_16,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr5_out* _out);

typedef struct Main_controller__main_ctrlr6_out {
  Main__version_type c_rs_ver;
} Main_controller__main_ctrlr6_out;

void Main_controller__main_ctrlr6_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_img_ver,
                                       Main__version_type c_me_imu_ver,
                                       Main__version_type c_oa_ver,
                                       Main__version_type c_sl_ver,
                                       Main__version_type c_tl_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int obj_14,
                                       int obj_15, int obj_16, int obj_17,
                                       int pnr, int pnr_1, int pnr_10,
                                       int pnr_11, int pnr_12, int pnr_13,
                                       int pnr_2, int pnr_3, int pnr_4,
                                       int pnr_5, int pnr_6, int pnr_7,
                                       int pnr_8, int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       Main__version_type pref_ver_14,
                                       Main__version_type pref_ver_15,
                                       Main__version_type pref_ver_16,
                                       Main__version_type pref_ver_17,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr6_out* _out);

typedef struct Main_controller__main_ctrlr7_out {
  Main__version_type c_rb_ver;
} Main_controller__main_ctrlr7_out;

void Main_controller__main_ctrlr7_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_img_ver,
                                       Main__version_type c_me_imu_ver,
                                       Main__version_type c_oa_ver,
                                       Main__version_type c_rs_ver,
                                       Main__version_type c_sl_ver,
                                       Main__version_type c_tl_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int obj_14,
                                       int obj_15, int obj_16, int obj_17,
                                       int obj_18, int pnr, int pnr_1,
                                       int pnr_10, int pnr_11, int pnr_12,
                                       int pnr_13, int pnr_2, int pnr_3,
                                       int pnr_4, int pnr_5, int pnr_6,
                                       int pnr_7, int pnr_8, int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       Main__version_type pref_ver_14,
                                       Main__version_type pref_ver_15,
                                       Main__version_type pref_ver_16,
                                       Main__version_type pref_ver_17,
                                       Main__version_type pref_ver_18,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr7_out* _out);

typedef struct Main_controller__main_ctrlr8_out {
  Main__version_type c_rpl_ver;
} Main_controller__main_ctrlr8_out;

void Main_controller__main_ctrlr8_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_img_ver,
                                       Main__version_type c_me_imu_ver,
                                       Main__version_type c_oa_ver,
                                       Main__version_type c_rb_ver,
                                       Main__version_type c_rs_ver,
                                       Main__version_type c_sl_ver,
                                       Main__version_type c_tl_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int obj_14,
                                       int obj_15, int obj_16, int obj_17,
                                       int obj_18, int obj_19, int pnr,
                                       int pnr_1, int pnr_10, int pnr_11,
                                       int pnr_12, int pnr_13, int pnr_2,
                                       int pnr_3, int pnr_4, int pnr_5,
                                       int pnr_6, int pnr_7, int pnr_8,
                                       int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       Main__version_type pref_ver_14,
                                       Main__version_type pref_ver_15,
                                       Main__version_type pref_ver_16,
                                       Main__version_type pref_ver_17,
                                       Main__version_type pref_ver_18,
                                       Main__version_type pref_ver_19,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr8_out* _out);

typedef struct Main_controller__main_ctrlr9_out {
  Main__version_type c_dt_ver;
} Main_controller__main_ctrlr9_out;

void Main_controller__main_ctrlr9_step(Main__version_type c_c_img_ver,
                                       int c_img_e, int c_img_r,
                                       Main__version_type c_me_img_ver,
                                       Main__version_type c_me_imu_ver,
                                       Main__version_type c_oa_ver,
                                       Main__version_type c_rb_ver,
                                       Main__version_type c_rpl_ver,
                                       Main__version_type c_rs_ver,
                                       Main__version_type c_sl_ver,
                                       Main__version_type c_tl_ver,
                                       Main__st_15 ck, Main__st_13 ck_10,
                                       Main__st_12 ck_13, Main__st_11 ck_16,
                                       Main__st_10 ck_19, Main__st_9 ck_22,
                                       Main__st_8 ck_25, Main__st_7 ck_28,
                                       Main__st_6 ck_31, Main__st_5 ck_34,
                                       Main__st_4 ck_37, Main__st_3 ck_39,
                                       Main__st_2 ck_41, Main__st_14 ck_7,
                                       int dt_e, int dt_r, int f_1, int f_2,
                                       int f_3, int max1, int max10,
                                       int max11, int max2, int max3,
                                       int max4, int max5, int max6,
                                       int max7, int max8, int max9,
                                       int me_img_e, int me_img_r,
                                       int me_imu_e, int me_imu_r, int min1,
                                       int min10, int min11, int min2,
                                       int min3, int min4, int min5,
                                       int min6, int min7, int min8,
                                       int min9, int oa_e, int oa_r,
                                       int obj_12, int obj_13, int obj_14,
                                       int obj_15, int obj_16, int obj_17,
                                       int obj_18, int obj_19, int obj_20,
                                       int pnr, int pnr_1, int pnr_10,
                                       int pnr_11, int pnr_12, int pnr_13,
                                       int pnr_2, int pnr_3, int pnr_4,
                                       int pnr_5, int pnr_6, int pnr_7,
                                       int pnr_8, int pnr_9,
                                       Main__version_type pref_ver_12,
                                       Main__version_type pref_ver_13,
                                       Main__version_type pref_ver_14,
                                       Main__version_type pref_ver_15,
                                       Main__version_type pref_ver_16,
                                       Main__version_type pref_ver_17,
                                       Main__version_type pref_ver_18,
                                       Main__version_type pref_ver_19,
                                       Main__version_type pref_ver_20,
                                       int pref_ver_task_assume_10_1,
                                       int pref_ver_task_assume_12,
                                       int pref_ver_task_assume_1_1,
                                       int pref_ver_task_assume_2_1,
                                       int pref_ver_task_assume_3_1,
                                       int pref_ver_task_assume_4_1,
                                       int pref_ver_task_assume_5_1,
                                       int pref_ver_task_assume_6_1,
                                       int pref_ver_task_assume_7_1,
                                       int pref_ver_task_assume_8_1,
                                       int pref_ver_task_assume_9_1,
                                       int pref_ver_task_guarantee_10_1,
                                       int pref_ver_task_guarantee_12,
                                       int pref_ver_task_guarantee_1_1,
                                       int pref_ver_task_guarantee_2_1,
                                       int pref_ver_task_guarantee_3_1,
                                       int pref_ver_task_guarantee_4_1,
                                       int pref_ver_task_guarantee_5_1,
                                       int pref_ver_task_guarantee_6_1,
                                       int pref_ver_task_guarantee_7_1,
                                       int pref_ver_task_guarantee_8_1,
                                       int pref_ver_task_guarantee_9_1,
                                       int rb_e, int rb_r, int rp_1,
                                       int rp_2, int rp_3, int rpl_e,
                                       int rpl_r, int rs_e, int rs_r,
                                       int sl_e, int sl_r, int texe1,
                                       int texe10, int texe11, int texe2,
                                       int texe3, int texe4, int texe5,
                                       int texe6, int texe7, int texe8,
                                       int texe9, int tl_e, int tl_r,
                                       int trk_e, int trk_r,
                                       Main_controller__main_ctrlr9_out* _out);

typedef struct Main_controller__main_ctrlr10_out {
  Main__version_type c_trk_ver;
} Main_controller__main_ctrlr10_out;

void Main_controller__main_ctrlr10_step(Main__version_type c_c_img_ver,
                                        Main__version_type c_dt_ver,
                                        int c_img_e, int c_img_r,
                                        Main__version_type c_me_img_ver,
                                        Main__version_type c_me_imu_ver,
                                        Main__version_type c_oa_ver,
                                        Main__version_type c_rb_ver,
                                        Main__version_type c_rpl_ver,
                                        Main__version_type c_rs_ver,
                                        Main__version_type c_sl_ver,
                                        Main__version_type c_tl_ver,
                                        Main__st_15 ck, Main__st_13 ck_10,
                                        Main__st_12 ck_13, Main__st_11 ck_16,
                                        Main__st_10 ck_19, Main__st_9 ck_22,
                                        Main__st_8 ck_25, Main__st_7 ck_28,
                                        Main__st_6 ck_31, Main__st_5 ck_34,
                                        Main__st_4 ck_37, Main__st_3 ck_39,
                                        Main__st_2 ck_41, Main__st_14 ck_7,
                                        int dt_e, int dt_r, int f_1, int f_2,
                                        int f_3, int max1, int max10,
                                        int max11, int max2, int max3,
                                        int max4, int max5, int max6,
                                        int max7, int max8, int max9,
                                        int me_img_e, int me_img_r,
                                        int me_imu_e, int me_imu_r, int min1,
                                        int min10, int min11, int min2,
                                        int min3, int min4, int min5,
                                        int min6, int min7, int min8,
                                        int min9, int oa_e, int oa_r,
                                        int obj_12, int obj_13, int obj_14,
                                        int obj_15, int obj_16, int obj_17,
                                        int obj_18, int obj_19, int obj_20,
                                        int obj_21, int pnr, int pnr_1,
                                        int pnr_10, int pnr_11, int pnr_12,
                                        int pnr_13, int pnr_2, int pnr_3,
                                        int pnr_4, int pnr_5, int pnr_6,
                                        int pnr_7, int pnr_8, int pnr_9,
                                        Main__version_type pref_ver_12,
                                        Main__version_type pref_ver_13,
                                        Main__version_type pref_ver_14,
                                        Main__version_type pref_ver_15,
                                        Main__version_type pref_ver_16,
                                        Main__version_type pref_ver_17,
                                        Main__version_type pref_ver_18,
                                        Main__version_type pref_ver_19,
                                        Main__version_type pref_ver_20,
                                        Main__version_type pref_ver_21,
                                        int pref_ver_task_assume_10_1,
                                        int pref_ver_task_assume_12,
                                        int pref_ver_task_assume_1_1,
                                        int pref_ver_task_assume_2_1,
                                        int pref_ver_task_assume_3_1,
                                        int pref_ver_task_assume_4_1,
                                        int pref_ver_task_assume_5_1,
                                        int pref_ver_task_assume_6_1,
                                        int pref_ver_task_assume_7_1,
                                        int pref_ver_task_assume_8_1,
                                        int pref_ver_task_assume_9_1,
                                        int pref_ver_task_guarantee_10_1,
                                        int pref_ver_task_guarantee_12,
                                        int pref_ver_task_guarantee_1_1,
                                        int pref_ver_task_guarantee_2_1,
                                        int pref_ver_task_guarantee_3_1,
                                        int pref_ver_task_guarantee_4_1,
                                        int pref_ver_task_guarantee_5_1,
                                        int pref_ver_task_guarantee_6_1,
                                        int pref_ver_task_guarantee_7_1,
                                        int pref_ver_task_guarantee_8_1,
                                        int pref_ver_task_guarantee_9_1,
                                        int rb_e, int rb_r, int rp_1,
                                        int rp_2, int rp_3, int rpl_e,
                                        int rpl_r, int rs_e, int rs_r,
                                        int sl_e, int sl_r, int texe1,
                                        int texe10, int texe11, int texe2,
                                        int texe3, int texe4, int texe5,
                                        int texe6, int texe7, int texe8,
                                        int texe9, int tl_e, int tl_r,
                                        int trk_e, int trk_r,
                                        Main_controller__main_ctrlr10_out* _out);

typedef struct Main_controller__main_ctrlr11_out {
  int c_c_img_pref;
  int c_dt_pref;
  int c_me_img_pref;
  int c_me_imu_pref;
  int c_oa_pref;
  int c_rb_pref;
  int c_rpl_pref;
  int c_rs_pref;
  int c_sl_pref;
  int c_tl_pref;
  int c_trk_pref;
} Main_controller__main_ctrlr11_out;

void Main_controller__main_ctrlr11_step(Main__version_type c_c_img_ver,
                                        Main__version_type c_dt_ver,
                                        int c_img_e, int c_img_r,
                                        Main__version_type c_me_img_ver,
                                        Main__version_type c_me_imu_ver,
                                        Main__version_type c_oa_ver,
                                        Main__version_type c_rb_ver,
                                        Main__version_type c_rpl_ver,
                                        Main__version_type c_rs_ver,
                                        Main__version_type c_sl_ver,
                                        Main__version_type c_tl_ver,
                                        Main__version_type c_trk_ver,
                                        Main__st_15 ck, Main__st_13 ck_10,
                                        Main__st_12 ck_13, Main__st_11 ck_16,
                                        Main__st_10 ck_19, Main__st_9 ck_22,
                                        Main__st_8 ck_25, Main__st_7 ck_28,
                                        Main__st_6 ck_31, Main__st_5 ck_34,
                                        Main__st_4 ck_37, Main__st_3 ck_39,
                                        Main__st_2 ck_41, Main__st_14 ck_7,
                                        int dt_e, int dt_r, int f_1, int f_2,
                                        int f_3, int max1, int max10,
                                        int max11, int max2, int max3,
                                        int max4, int max5, int max6,
                                        int max7, int max8, int max9,
                                        int me_img_e, int me_img_r,
                                        int me_imu_e, int me_imu_r, int min1,
                                        int min10, int min11, int min2,
                                        int min3, int min4, int min5,
                                        int min6, int min7, int min8,
                                        int min9, int oa_e, int oa_r,
                                        int obj_12, int obj_13, int obj_14,
                                        int obj_15, int obj_16, int obj_17,
                                        int obj_18, int obj_19, int obj_20,
                                        int obj_21, int obj_22, int pnr,
                                        int pnr_1, int pnr_10, int pnr_11,
                                        int pnr_12, int pnr_13, int pnr_2,
                                        int pnr_3, int pnr_4, int pnr_5,
                                        int pnr_6, int pnr_7, int pnr_8,
                                        int pnr_9,
                                        Main__version_type pref_ver_12,
                                        Main__version_type pref_ver_13,
                                        Main__version_type pref_ver_14,
                                        Main__version_type pref_ver_15,
                                        Main__version_type pref_ver_16,
                                        Main__version_type pref_ver_17,
                                        Main__version_type pref_ver_18,
                                        Main__version_type pref_ver_19,
                                        Main__version_type pref_ver_20,
                                        Main__version_type pref_ver_21,
                                        Main__version_type pref_ver_22,
                                        int pref_ver_task_assume_10_1,
                                        int pref_ver_task_assume_12,
                                        int pref_ver_task_assume_1_1,
                                        int pref_ver_task_assume_2_1,
                                        int pref_ver_task_assume_3_1,
                                        int pref_ver_task_assume_4_1,
                                        int pref_ver_task_assume_5_1,
                                        int pref_ver_task_assume_6_1,
                                        int pref_ver_task_assume_7_1,
                                        int pref_ver_task_assume_8_1,
                                        int pref_ver_task_assume_9_1,
                                        int pref_ver_task_guarantee_10_1,
                                        int pref_ver_task_guarantee_12,
                                        int pref_ver_task_guarantee_1_1,
                                        int pref_ver_task_guarantee_2_1,
                                        int pref_ver_task_guarantee_3_1,
                                        int pref_ver_task_guarantee_4_1,
                                        int pref_ver_task_guarantee_5_1,
                                        int pref_ver_task_guarantee_6_1,
                                        int pref_ver_task_guarantee_7_1,
                                        int pref_ver_task_guarantee_8_1,
                                        int pref_ver_task_guarantee_9_1,
                                        int rb_e, int rb_r, int rp_1,
                                        int rp_2, int rp_3, int rpl_e,
                                        int rpl_r, int rs_e, int rs_r,
                                        int sl_e, int sl_r, int texe1,
                                        int texe10, int texe11, int texe2,
                                        int texe3, int texe4, int texe5,
                                        int texe6, int texe7, int texe8,
                                        int texe9, int tl_e, int tl_r,
                                        int trk_e, int trk_r,
                                        Main_controller__main_ctrlr11_out* _out);

typedef struct Main_controller__pref_ver_task_ctrlr0_out {
  int c_best;
  Main__version_type c_pref_ver;
} Main_controller__pref_ver_task_ctrlr0_out;

void Main_controller__pref_ver_task_ctrlr0_step(int current_texec,
                                                Main__version_type task_ver,
                                                int texec_h1_11,
                                                int texec_h2_11,
                                                int texec_h3_11,
                                                int texec_sw_11, int tmax,
                                                int tmin,
                                                Main_controller__pref_ver_task_ctrlr0_out* _out);

#endif // MAIN_CONTROLLER_H
