

#gcc -o sim main_c/main_types.c main_controller_c/main_controller.c main_controller_c/main_controller_types.c



gcc -o sim _main.c  main.c  main_controller.c  main_controller.h  main_controller_types.c  main_controller_types.h  _main.h  main.h  main_types.c  main_types.h  Makefile  math.c  math.h  pervasives.h



gcc  -o test  _main.c  main.c  main_controller.c  main_controller_types.c  main_types.c  math.c -lm

#gcc -o sim  -Iheptagon -Imain_c -I. -Imain_controller_c _main.c call.c main_c/main.c main_c/main_types.c main_controller_c/main_controller.c main_controller_c/main_controller_types.c
